# -*- coding: utf-8 -*-
"""Modelo_detector_IDONO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I57KA_P7YYRDf1gU0zeVhCq6GcljKMOq
"""

!pip install scikit-learn seaborn scipy pillow matplotlib

import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from scipy import stats
from scipy.ndimage import gaussian_filter
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    classification_report, confusion_matrix,
    ConfusionMatrixDisplay, precision_recall_curve
)
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from google.colab import drive
drive.mount('/content/drive')

"""modelo de clasificacion. vectores:

FFT: espectral
HSI: buscar cual es la mas descriptiva

**ETAPA 1: CREAR VECTOR DE FEATURES**

# HSI
"""

def rgb_to_hsi(image_rgb):
    img = np.array(image_rgb).astype(np.float64) / 255.0
    R, G, B = img[:, :, 0], img[:, :, 1], img[:, :, 2]
    I = (R + G + B) / 3.0
    min_rgb = np.minimum(np.minimum(R, G), B)
    S = np.where(I > 0, 1.0 - (3.0 / (R + G + B + 1e-8)) * min_rgb, 0.0)
    num   = 0.5 * ((R - G) + (R - B))
    den   = np.sqrt((R - G)**2 + (R - B) * (G - B)) + 1e-8
    theta = np.arccos(np.clip(num / den, -1.0, 1.0))

    H = np.where(B <= G, theta, 2 * np.pi - theta)
    H = H / (2 * np.pi)

    return H, S, I

def HSI_feature(img_rgb: np.ndarray) -> list:
    img_pil = Image.fromarray(img_rgb.astype(np.uint8))
    H, S, I = rgb_to_hsi(img_pil)

    feats = []
    for canal in [H,S,I]:
        flat = canal.flatten()
        feats += [
          float(flat.mean()),
          float(flat.std()),
        ]

    return feats

"""# FFT"""

import matplotlib.colors as mcolors
def FFT_features(img_rgb):
    img_hsv = mcolors.rgb_to_hsv(np.array(img_rgb) / 255.0)
    v_channel = img_hsv[:,:,2]
    feat_fft = []
    for i, name in enumerate(['Hue', 'Sat', 'Val']):
        channel = img_hsv[:,:,i]
        fft = np.fft.fft2(channel)
        mag = np.abs(np.fft.fftshift(fft))
        log_mag = np.log1p(mag)

        feat_fft += [
            log_mag.mean(),
            log_mag.std(),
            np.max(log_mag)
        ]
    return np.array(feat_fft)

"""# CARGAR IMAGENES Y EXTRAER FEATURES"""

def extract_features(img_path: str) -> np.ndarray:
    img_rgb = np.array(Image.open(img_path).convert('RGB').resize((255,255)))
    feat_fft = FFT_features(img_rgb)
    feat_hsi = HSI_feature(img_rgb)
    feature_vector = np.array( list(feat_fft) + list(feat_hsi),
    dtype=np.float32
)

    return feature_vector

def load_dataset(base_path,suffix=""):
    X, y, groups = [], [], []
    n=0
    class_map = {
        f"clean{suffix}":    0,
        f"bicubic{suffix}":  1,
        f"bilinear{suffix}": 1,
    }

    for folder, label in class_map.items():
        folder_path = os.path.join(base_path, folder)
        if not os.path.exists(folder_path):
            print(f"NO: {folder_path}")
            continue

        files = [f for f in os.listdir(folder_path)
                 if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

        for fname in files:
            fpath = os.path.join(folder_path, fname)
            print(fpath)
            try:
                feat = extract_features(fpath)
                X.append(feat)
                y.append(label)
                groups.append(folder)
                n=n+1
            except Exception as e:
                print(f"Error con {fname}: {e}")
    print(n)

    return np.array(X), np.array(y), groups
BASE = "/content/drive/MyDrive/Imagenes tesis"

TRAIN_PATH = os.path.join(BASE, "train_data")
TEST_PATH  = os.path.join(BASE, "test_data")

print("Cargando train...")
X_train, y_train, groups_train = load_dataset(TRAIN_PATH, suffix="_train")

print("Cargando test...")
X_test, y_test, groups_test = load_dataset(TEST_PATH, suffix="_test")

"""recuento de features para validacion y nombramiento de variables."""

FFT_CHANNELS = ['Hue', 'Sat', 'Val']
FFT_STATS = ['fft_mean', 'fft_std', 'fft_max']
HSI_CHANNELS = ['H', 'S','I']
HSI_STATS = ['mean', 'std']

feature_names = ( [f"FFT_{s}_{c}" for c in FFT_CHANNELS for s in FFT_STATS]    # 9
  + [f"HSI_{s}_{ch}" for ch in HSI_CHANNELS for s in HSI_STATS]  # 6
)
print(f"Total de features: {len(feature_names)}")

"""GRAFICO DE DENSIDAD USANDO LAS FEATURES

Se grafica cada vector de caracteristicas comparando la densidad mostrando asi que features encuentran mas variabilidad entre una imagen de ataque y una limpia.
"""

import matplotlib.pyplot as plt
import numpy as np

# Máscaras por clase
mask_clean   = y_train == 0
mask_ataque  = y_train == 1

# Índices de cada familia
idx_fft  = [i for i, n in enumerate(feature_names) if n.startswith('FFT')]
idx_hsi  = [i for i, n in enumerate(feature_names) if n.startswith('HSI')]
print(f"FFT:      {idx_fft}")
print(f"HSI:      {idx_hsi}")

def plot_familia(indices, titulo, filename):
    n = len(indices)
    cols = 7
    rows = int(np.ceil(n / cols))

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 3, rows * 2.5))
    axes = axes.flatten()

    for i, feat_idx in enumerate(indices):
        ax = axes[i]
        vals_clean  = X_train[mask_clean,  feat_idx]
        vals_ataque = X_train[mask_ataque, feat_idx]

        ax.hist(vals_clean,  bins=15, alpha=0.6, color='steelblue',
                label='clean',   density=True)
        ax.hist(vals_ataque, bins=15, alpha=0.6, color='darkorange',
                label='ataque',  density=True)

        ax.set_title(feature_names[feat_idx], fontsize=7)
        ax.tick_params(labelsize=6)
        ax.set_yticks([])

        if i == 0:
            ax.legend(fontsize=6)

    # Apagar subplots vacíos
    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)

    fig.suptitle(titulo, fontsize=13, fontweight='bold', y=1.01)
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Guardado: {filename}")

plot_familia(idx_fft,  "Distribución features — FFT  (9 features)",  "dist_fft.png")
plot_familia(idx_hsi,  "Distribución features — HSI  (6 features)",  "dist_hsi.png")

from scipy.stats import ks_2samp

separabilidad = {}
for i, name in enumerate(feature_names):
    stat, p = ks_2samp(X_train[mask_clean, i], X_train[mask_ataque, i])
    separabilidad[name] = stat  # más cercano a 1 = más separable

import pandas as pd
df_sep = pd.Series(separabilidad).sort_values(ascending=False)
print(df_sep)

"""de estas seguiria limpiando y sacaria las que se superponen mucho no?

# ENTRENAMIENTO DEL MODELO USANDO
"""

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    classification_report, accuracy_score,
    precision_score, recall_score, f1_score
)
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

# Pipeline: escalar + SVM
pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='rbf', probability=True))
])

# Búsqueda de hiperparámetros
param_grid = {
    'svm__C':     [0.1, 1, 10, 100],
    'svm__gamma': ['scale', 'auto', 0.01, 0.1]
}

# Cross-validation estratificada
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# GridSearch: encuentra los mejores hiperparámetros sobre X_train
grid = GridSearchCV(pipe, param_grid, cv=cv, scoring='f1', n_jobs=-1, verbose=1)
grid.fit(X_train, y_train)

# Mejor modelo (ya tiene el scaler ajustado correctamente)
best_model = grid.best_estimator_
print(f"Mejores hiperparámetros: {grid.best_params_}")
print(f"Mejor F1 en validación (CV): {grid.best_score_:.4f}\n")

# Evaluación final sobre X_test (una sola vez)
y_pred = best_model.predict(X_test)

print("Accuracy: ",  accuracy_score(y_test, y_pred))
print("Precision:",  precision_score(y_test, y_pred))
print("Recall:   ",  recall_score(y_test, y_pred))
print("F1-score: ",  f1_score(y_test, y_pred))
print("\nReporte completo:")
print(classification_report(y_test, y_pred))

from sklearn.inspection import permutation_importance
import pandas as pd
import matplotlib.pyplot as plt

result = permutation_importance(
    best_model,          # tu mejor estimador del GridSearchCV
    X_test, y_test,
    n_repeats=30,        # repeticiones para mayor estabilidad
    random_state=42,
    scoring='f1',        # misma métrica que usaste en el grid search
    n_jobs=-1
)

# Armar DataFrame ordenado
perm_df = pd.DataFrame({
    'feature':    feature_names,
    'importance': result.importances_mean,
    'std':        result.importances_std
}).sort_values('importance', ascending=False)

print(perm_df.to_string(index=False))

from sklearn.metrics import classification_report, ConfusionMatrixDisplay

best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)

print(classification_report(y_test, y_pred, target_names=['clean', 'ataque']))
ConfusionMatrixDisplay.from_estimator(best_model, X_test, y_test)
plt.show()

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

def downsample_como_anamorpher(img_path, target_size=(512, 512)):
    img = Image.open(img_path).convert('RGB')
    img_down = img.resize(target_size,  Image.NEAREST)

    return img_down


def mostrar_downsampled(img_path, target_size=(512, 512), method='nearest'):
    img_orig = Image.open(img_path).convert('RGB')
    img_down = downsample_como_anamorpher(img_path, target_size, method)

    fig, axes = plt.subplots(1, 2, figsize=(10, 5))

    axes[0].imshow(img_orig)
    axes[0].set_title(f"Original  {img_orig.size[0]}×{img_orig.size[1]}", fontsize=11)
    axes[0].axis('off')

    axes[1].imshow(img_down)
    axes[1].set_title(f"Downsampled ({method})  {target_size[0]}×{target_size[1]}", fontsize=11)
    axes[1].axis('off')

    plt.tight_layout()
    plt.show()

    return img_down

def predecir_imagen(img_path, modelo, target_size=(255, 255)):
    """
    Hace downsampling igual que Anamorpher y predice con el modelo entrenado.
    """
    # 1. Downsampling como Anamorpher
    img_down = downsample_como_anamorpher(img_path, target_size)
    img_rgb  = np.array(img_down)

    # 2. Extraer features (mismo pipeline que en el dataset)
    feat_fft = FFT_features(img_rgb)
    feat_hsi = HSI_feature(img_rgb)
    feat     = np.array(list(feat_fft) + list(feat_hsi), dtype=np.float32).reshape(1, -1)

    # 3. Predecir
    pred = modelo.predict(feat)[0]
    prob = modelo.predict_proba(feat)[0]
    etiqueta = "CLEAN" if pred == 0 else "ATAQUE (interpolada)"

    # 4. Mostrar
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))
    img_orig = Image.open(img_path).convert('RGB')
    axes[0].imshow(img_orig)
    axes[0].set_title("Original", fontsize=11)
    axes[0].axis('off')

    axes[1].imshow(img_down)
    color = 'red' if pred == 1 else 'green'
    axes[1].set_title(
        f"{etiqueta}\nP(clean)={prob[0]:.3f}  P(ataque)={prob[1]:.3f}",
        fontsize=10, color=color
    )
    axes[1].axis('off')
    plt.tight_layout()
    plt.show()

    return {"label": etiqueta, "pred": pred, "proba": prob}

resultado = predecir_imagen(
    "/content/drive/MyDrive/Imagenes tesis/nearest_demo.png",
    modelo,
    target_size=(255, 255),  # el mismo tamaño que usaste al entrenar
)

import joblib

joblib.dump(modelo, '/content/drive/MyDrive/Imagenes tesis/Modelo_IDONO.pkl')
print("Modelo guardado.")