# -*- coding: utf-8 -*-
"""pipelineFinal_imagen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMN1dWNzUQq40-cfHafENRKcS7k0Hhxs
"""

!sudo apt install -y tesseract-ocr
!pip install -q pytesseract Levenshtein Pillow scikit-learn seaborn scipy matplotlib opencv-python-headless joblib

import os, re
import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from collections import Counter
from PIL import Image

import pytesseract
from pytesseract import Output

import joblib
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, GridSearchCV

try:
    from Levenshtein import distance as _lev_lib
except Exception:
    _lev_lib = None

from google.colab import drive
drive.mount('/content/drive')

BASE        = "/content/drive/MyDrive/Imagenes tesis"
MODELO_PKL  = os.path.join(BASE, "Modelo_IDONO.pkl")
SANITIZADAS = os.path.join(BASE, "Sanitizadas/SanitizadasPipeline")
os.makedirs(SANITIZADAS, exist_ok=True)

"""# DETECTOR

FEATURES DEL DETECTOR  (FFT + HSI)
"""

def rgb_to_hsi(image_rgb):
    img = np.array(image_rgb).astype(np.float64) / 255.0
    R, G, B = img[:, :, 0], img[:, :, 1], img[:, :, 2]
    I = (R + G + B) / 3.0
    min_rgb = np.minimum(np.minimum(R, G), B)
    S = np.where(I > 0, 1.0 - (3.0 / (R + G + B + 1e-8)) * min_rgb, 0.0)
    num   = 0.5 * ((R - G) + (R - B))
    den   = np.sqrt((R - G) ** 2 + (R - B) * (G - B)) + 1e-8
    theta = np.arccos(np.clip(num / den, -1.0, 1.0))
    H = np.where(B <= G, theta, 2 * np.pi - theta) / (2 * np.pi)
    return H, S, I


def HSI_feature(img_rgb):
    H, S, I = rgb_to_hsi(Image.fromarray(img_rgb.astype(np.uint8)))
    feats = []
    for canal in [H, S, I]:
        flat = canal.flatten()
        feats += [float(flat.mean()), float(flat.std())]
    return feats


def FFT_features(img_rgb):
    img_hsv = mcolors.rgb_to_hsv(np.array(img_rgb) / 255.0)
    feat_fft = []
    for i in range(3):
        channel = img_hsv[:, :, i]
        mag     = np.abs(np.fft.fftshift(np.fft.fft2(channel)))
        log_mag = np.log1p(mag)
        feat_fft += [log_mag.mean(), log_mag.std(), np.max(log_mag)]
    return np.array(feat_fft)


def extract_features(img_path):
    """Mismo preprocesamiento que en el entrenamiento: resize a 255x255."""
    img_rgb = np.array(Image.open(img_path).convert('RGB').resize((255, 255)))
    return np.array(list(FFT_features(img_rgb)) + list(HSI_feature(img_rgb)),
                    dtype=np.float32)

"""OCR + CONSENSO"""

def preprocess_for_ocr(pil_img, mode='raw'):
    img = np.array(pil_img)
    if mode == 'adaptive':
        hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
        h, s, v = cv2.split(hsv)
        s = np.clip(cv2.multiply(s, 3), 0, 255).astype(np.uint8)
        img_sat = cv2.cvtColor(cv2.merge([h, s, v]), cv2.COLOR_HSV2RGB)
        img_exp = cv2.convertScaleAbs(img_sat, alpha=2.5, beta=50)
        gray = cv2.cvtColor(img_exp, cv2.COLOR_RGB2GRAY)
        clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
        enhanced = clahe.apply(gray)
        return cv2.adaptiveThreshold(enhanced, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                     cv2.THRESH_BINARY, 11, 2)
    return img



def downscale_and_ocr_data(image_file, target_size, scale_method='bilinear',
                           prep_mode='adaptive', min_conf=30):
    img = Image.open(image_file).convert('RGB')
    if isinstance(target_size, int):
        target_size = (target_size, target_size)
    methods = {'bilinear': Image.Resampling.BILINEAR,
               'bicubic':  Image.Resampling.BICUBIC,
               'nearest':  Image.Resampling.NEAREST}
    downscaled = img.resize(target_size, resample=methods[scale_method])
    processed  = preprocess_for_ocr(downscaled, mode=prep_mode)
    H, W = processed.shape[:2]
    data = pytesseract.image_to_data(processed, config=r'--oem 3 --psm 11',
                                     output_type=Output.DICT)
    words = []
    for i in range(len(data['text'])):
        try:   conf = int(data['conf'][i])
        except ValueError: conf = -1
        w = data['text'][i].strip()
        if conf > min_conf and w and any(c.isalnum() for c in w):
            x, y, ww, hh = (data['left'][i], data['top'][i],
                            data['width'][i], data['height'][i])
            words.append({'word': w, 'conf': conf,
                          'cx': (x + ww / 2) / W, 'cy': (y + hh / 2) / H,
                          'box_norm': (x / W, y / H, ww / W, hh / H)})
    return {'image': processed, 'size': target_size, 'method': scale_method, 'words': words}


def _lev(a, b):
    if _lev_lib is not None:
        return _lev_lib(a, b)
    m, n = len(a), len(b)
    if not m: return n
    prev = list(range(n + 1))
    for i in range(1, m + 1):
        cur = [i] + [0] * n
        for j in range(1, n + 1):
            cur[j] = min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] != b[j - 1]))
        prev = cur
    return prev[n]


def _norm(w):
    return re.sub(r'[^A-Z0-9]', '', w.upper())


def consenso_texto(image_path, scale_methods=('bilinear', 'bicubic', 'nearest'),
                   sizes=(255, 512, 800, 1092, 1600), prep_mode='adaptive',
                   min_conf=30, min_votos=4, pos_tol=0.06, sim_tol=0.34, min_len=2):
    # 1. recolectar TODAS las detecciones de las 12 reconstrucciones
    dets = []
    for m in scale_methods:
        for s in sizes:
            for wd in downscale_and_ocr_data(image_path, s, m, prep_mode, min_conf)['words']:
                nw = _norm(wd['word'])
                if nw:
                    dets.append({**wd, 'nword': nw, 'src': (m, s)})

    # 2. agrupar por palabra parecida + posicion cercana (semilla = mayor conf)
    grupos = []
    for d in sorted(dets, key=lambda x: -x['conf']):
        for g in grupos:
            cerca = abs(d['cx'] - g['cx']) < pos_tol and abs(d['cy'] - g['cy']) < pos_tol
            ml = max(len(d['nword']), len(g['rep']))
            igual = (ml and _lev(d['nword'], g['rep']) / ml <= sim_tol)
            if cerca and igual:
                g['items'].append(d); g['srcs'].add(d['src'])
                g['cx'] = np.mean([it['cx'] for it in g['items']])
                g['cy'] = np.mean([it['cy'] for it in g['items']])
                break
        else:
            grupos.append({'rep': d['nword'], 'cx': d['cx'], 'cy': d['cy'],
                           'items': [d], 'srcs': {d['src']}})

    # 3. quedarse con los votados por >= min_votos reconstrucciones distintas
    fuertes = [g for g in grupos if len(g['srcs']) >= min_votos]
    for g in fuertes:
        g['palabra']  = Counter(it['nword'] for it in g['items']).most_common(1)[0][0]
        g['votos']    = len(g['srcs'])
        g['conf']     = float(np.mean([it['conf'] for it in g['items']]))
        g['box_norm'] = tuple(np.median(np.array([it['box_norm'] for it in g['items']]), axis=0))

    # 3.b descartar "letras sueltas": tokens de 1 caracter son ruido del fondo
    #     texturado (votan alto por ser consistentes, no porque sean texto real)
    fuertes = [g for g in fuertes if len(g['palabra']) >= min_len]

    # 4. ordenar en lectura: por renglon (cy) y luego por x
    fuertes.sort(key=lambda g: (round(g['cy'] / 0.05), g['cx']))
    return {'texto': ' '.join(g['palabra'] for g in fuertes),
            'palabras': [{'palabra': g['palabra'], 'votos': g['votos'],
                          'conf': round(g['conf'], 1),
                          'box_norm': tuple(np.round(g['box_norm'], 3))} for g in fuertes]}

"""# SANITIZADOR

INPAINT usando lo que detecto OCR
"""

def filas_dominantes(palabras, y_tol=0.04, min_frac=0.5):
    """Agrupa palabras en renglones (por cy) y conserva los que concentran la mayoria
       de los votos -> filtra detecciones sueltas."""
    rows = []
    for p in sorted(palabras, key=lambda q: q['box_norm'][1]):
        y = p['box_norm'][1]
        for r in rows:
            if abs(r['cy'] - y) < y_tol:
                r['items'].append(p)
                r['cy'] = np.mean([it['box_norm'][1] for it in r['items']]); break
        else:
            rows.append({'cy': y, 'items': [p]})
    for r in rows:
        r['votos'] = sum(it['votos'] for it in r['items'])
    if not rows: return []
    maxv = max(r['votos'] for r in rows)
    return [r for r in rows if r['votos'] >= min_frac * maxv]

def sanitizar_por_consenso(image_path, res, output_folder=SANITIZADAS,
                           method='telea', pad_frac=0.03, radius=3,
                           max_cobertura=0.45):
    img = cv2.imread(image_path); H, W = img.shape[:2]
    mask = np.zeros((H, W), np.uint8); pad = int(pad_frac * H)

    filas = filas_dominantes(res['palabras'])
    if filas:
        filas = sorted(filas, key=lambda r: r['cy'])
        bloques = [[filas[0]]]
        for r in filas[1:]:
            (bloques[-1].append(r) if abs(r['cy'] - bloques[-1][-1]['cy']) < 0.08
              else bloques.append([r]))
        for b in bloques:
            tops = [it['box_norm'][1] for r in b for it in r['items']]
            bots = [it['box_norm'][1] + it['box_norm'][3] for r in b for it in r['items']]
            y0 = max(0, int(min(tops)*H) - pad); y1 = min(H, int(max(bots)*H) + pad)
            mask[y0:y1, :] = 255

    cobertura = float((mask > 0).mean())          # fraccion de imagen que se taparia

    # --- GATE: si el texto domina la imagen, no tiene sentido reconstruir ---
    if cobertura > max_cobertura:
        return {'sanitized': None, 'mask': mask, 'out_path': None,
                'cobertura': cobertura, 'rechazada': True}

    flag = cv2.INPAINT_TELEA if method == 'telea' else cv2.INPAINT_NS
    sanitized = cv2.inpaint(img, mask, radius, flag) if mask.sum() else img.copy()
    out = os.path.join(output_folder, f"clean_{os.path.basename(image_path)}")
    cv2.imwrite(out, sanitized)
    return {'sanitized': sanitized, 'mask': mask, 'out_path': out,
            'cobertura': cobertura, 'rechazada': False}


def mostrar_sanitizado(image_path, san, vista=('bilinear', 512)):
    m, s = vista
    orig = cv2.cvtColor(cv2.imread(image_path), cv2.COLOR_BGR2RGB)
    sani = cv2.cvtColor(san['sanitized'], cv2.COLOR_BGR2RGB)

    # vista ByN tal cual la ve el OCR (adaptiveThreshold sobre la reconstruccion)
    byn_orig = downscale_and_ocr_data(image_path,     s, m)['image']
    byn_sani = downscale_and_ocr_data(san['out_path'], s, m)['image']

    fig, ax = plt.subplots(2, 3, figsize=(15, 9))
    ax[0, 0].imshow(orig);                     ax[0, 0].set_title("Original")
    ax[0, 1].imshow(san['mask'], cmap='gray'); ax[0, 1].set_title("Mascara")
    ax[0, 2].imshow(sani);                     ax[0, 2].set_title("Sanitizada (inpaint)")
    ax[1, 0].imshow(byn_orig, cmap='gray');    ax[1, 0].set_title(f"ByN OCR — original ({m} {s}px)")
    ax[1, 2].imshow(byn_sani, cmap='gray');    ax[1, 2].set_title(f"ByN OCR — sanitizada ({m} {s}px)")
    for a in ax.ravel():
        a.axis('off')
    plt.tight_layout(); plt.show()

"""MEDIAN BLUR"""

def model_robust_median(image_path, output_folder=SANITIZADAS, ksize=5):
    img       = cv2.imread(image_path)
    sanitized = cv2.medianBlur(img, ksize)
    out = os.path.join(output_folder, f"median_{os.path.basename(image_path)}")
    cv2.imwrite(out, sanitized)
    return {'sanitized': sanitized, 'out_path': out, 'ksize': ksize}

"""# OUTPUTS

MODELO DETECTOR
"""

def downsample_revelado(img_path, target_size=(800, 800), method='bilinear'):
    methods = {'nearest':  Image.Resampling.NEAREST,
               'bilinear': Image.Resampling.BILINEAR,
               'bicubic':  Image.Resampling.BICUBIC}
    return Image.open(img_path).convert('RGB').resize(target_size, methods[method])


def realzar_para_lectura(pil_img, sat_mult=3, alpha=2.5, beta=50):
    """Realza la escalada SIN binarizar -> deja el texto oculto legible a color.
       Es el mismo front de preprocess_for_ocr('adaptive') (saturacion + exposicion)
       pero cortando antes del gris/CLAHE/threshold, para que se vea como lo lee el ojo."""
    img = np.array(pil_img)                          # RGB
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    h, s, v = cv2.split(hsv)
    s = np.clip(cv2.multiply(s, sat_mult), 0, 255).astype(np.uint8)   # +saturacion
    img_sat = cv2.cvtColor(cv2.merge([h, s, v]), cv2.COLOR_HSV2RGB)
    img_exp = cv2.convertScaleAbs(img_sat, alpha=alpha, beta=beta)    # +exposicion/contraste
    return img_exp


def mostrar_deteccion(img_path, etiqueta, prob, target_size=(512, 512), method='nearest'):
    """Paso 2: original | escalada (revela el ataque) | escalada realzada (texto legible)."""
    orig     = Image.open(img_path).convert('RGB')
    rev      = downsample_revelado(img_path, target_size, method)
    realzada = realzar_para_lectura(rev)

    fig, ax = plt.subplots(1, 3, figsize=(16, 5))
    ax[0].imshow(orig); ax[0].set_title(f"Original  {orig.size[0]}x{orig.size[1]}")

    color = 'red' if etiqueta.startswith('ATAQUE') else 'green'
    ax[1].imshow(rev)
    ax[1].set_title(f"Escalada {method} {target_size[0]}x{target_size[1]}\n"
                    f"{etiqueta}   P(clean)={prob[0]:.3f}  P(ataque)={prob[1]:.3f}",
                    color=color)

    ax[2].imshow(realzada)
    ax[2].set_title("Realzada (saturacion x3 + exposicion)\ntexto legible")

    for a in ax:
        a.axis('off')
    plt.tight_layout(); plt.show()

""" OCR"""

def mostrar_consenso(image_path, res, sobre=('bilinear', 512)):
    """Dibuja las cajas del consenso (en rojo) con la palabra y la cantidad de votos.
       sobre=('metodo', size) -> sobre una reconstruccion (se ve el texto).
       sobre=None             -> sobre la imagen ORIGINAL (lo que sanitiza el pipeline)."""
    if sobre is None:
        img = np.array(Image.open(image_path).convert('RGB'))
    else:
        m, s = sobre
        proc = downscale_and_ocr_data(image_path, s, m)['image']
        img  = cv2.cvtColor(proc, cv2.COLOR_GRAY2RGB) if proc.ndim == 2 else proc.copy()

    H, W = img.shape[:2]
    vis = img.copy()
    th = max(1, W // 500); fs = max(0.4, W / 1500)
    for p in res['palabras']:
        x, y, w, h = p['box_norm']
        x0, y0, x1, y1 = int(x * W), int(y * H), int((x + w) * W), int((y + h) * H)
        cv2.rectangle(vis, (x0, y0), (x1, y1), (255, 0, 0), th)
        cv2.putText(vis, f"{p['palabra']}({p['votos']})", (x0, max(12, y0 - 4)),
                    cv2.FONT_HERSHEY_SIMPLEX, fs, (255, 0, 0), th, cv2.LINE_AA)

    plt.figure(figsize=(8, 8))
    plt.imshow(vis); plt.axis('off')
    plt.title(f"Consenso: {res['texto']}")
    plt.show()

def mostrar_grid_ocr(image_path, scale_methods=('bilinear', 'bicubic', 'nearest'),
                     sizes=(255, 512, 800, 1092), prep_mode='adaptive',
                     usar_error=False, umbral_error=80):
    resultados = []
    for method in scale_methods:
        for size in sizes:
            r    = downscale_and_ocr_data(image_path, size, scale_method=method, prep_mode=prep_mode)
            text = r['text']
            if usar_error:
                continue
            resultados.append({'img': r['image'],
                               'title': f"{method.upper()}\n{size}px",
                               'method': method, 'size': size,
                               'status': (text[:40].replace('\n', ' ') if text else "---"),
                               })
    n = len(resultados)
    if n == 0:
        print("Sin reconstrucciones para mostrar."); return
    fig, axes = plt.subplots(1, n, figsize=(n * 3, 3))
    if n == 1:
        axes = [axes]
    for ax, res in zip(axes, resultados):
        ax.imshow(res['img'], cmap='gray'); ax.set_title(res['title'], fontsize=9); ax.axis('off')
    plt.tight_layout(); plt.show()

    header = f"{'METODO':<10} | {'TAMANO':<8} | {'TEXTO ENCONTRADO':<42}"
    if usar_error: header += " | ERROR"
    print(header)
    print("-" * len(header))
    for res in resultados:
        line = f"{res['method'].upper():<10} | {str(res['size']):<8} | {res['status']:<42}"
        if usar_error: line += f" | {res['error']:.1f}"
        print(line)

""" Median BLUR"""

def mostrar_median(image_path, san, vista=('bilinear', 512)):
    m, s = vista
    orig = cv2.cvtColor(cv2.imread(image_path),  cv2.COLOR_BGR2RGB)
    sani = cv2.cvtColor(san['sanitized'],        cv2.COLOR_BGR2RGB)

    byn_orig = downscale_and_ocr_data(image_path,     s, m)['image']
    byn_sani = downscale_and_ocr_data(san['out_path'], s, m)['image']

    fig, ax = plt.subplots(2, 2, figsize=(10, 9))
    ax[0, 0].imshow(orig);                  ax[0, 0].set_title("Original")
    ax[0, 1].imshow(sani);                  ax[0, 1].set_title(f"Median blur (k={san['ksize']})")
    ax[1, 0].imshow(byn_orig, cmap='gray'); ax[1, 0].set_title(f"ByN OCR — original ({m} {s}px)")
    ax[1, 1].imshow(byn_sani, cmap='gray'); ax[1, 1].set_title(f"ByN OCR — median blur ({m} {s}px)")
    for a in ax.ravel():
        a.axis('off')
    plt.tight_layout(); plt.show()

"""Cargar el modelo"""

modelo = joblib.load(MODELO_PKL)

"""# EJECUCION PIPELINE"""

def pipeline(image_path, modelo, vista_metodo='nearest', vista_size=(512, 512)):
    print("=" * 80)
    print("IMAGEN:", os.path.basename(image_path))

    # --- PASO 2: DETECTOR ---
    feat = extract_features(image_path).reshape(1, -1)
    pred = int(modelo.predict(feat)[0])
    prob = modelo.predict_proba(feat)[0]
    etiqueta = "CLEAN" if pred == 0 else "ATAQUE (interpolada)"
    print(f"DETECTOR -> {etiqueta}   P(clean)={prob[0]:.3f}  P(ataque)={prob[1]:.3f}")
    mostrar_deteccion(image_path, etiqueta, prob, vista_size, vista_metodo)

    # --- PASO 3: RAMA SEGUN DETECCION ---
    if pred == 1:                                  # 3.1 ATAQUE
        res = consenso_texto(image_path)
        if res['palabras']:                        # 3.1.a hay texto -> consenso + inpaint
            print(f"OCR -> texto detectado: {res['texto']}")
            mostrar_consenso(image_path, res)
            san = sanitizar_por_consenso(image_path, res)

            if san['rechazada']:
                print(f"IMAGEN RECHAZADA: el texto oculto cubre {san['cobertura']*100:.0f}% "
                      f"del frame. No es recuperable -> se descarta en lugar de inpaint.")
                plt.imshow(san['mask'], cmap='gray'); plt.axis('off')
                plt.title(f"Mascara de rechazo ({san['cobertura']*100:.0f}% cobertura)"); plt.show()
            else:
                mostrar_sanitizado(image_path, san)
                res_post = consenso_texto(san['out_path'])
                print(f"  cobertura tapada: {san['cobertura']*100:.0f}%")
                print(f"  antes:   {res['texto']}")
                print(f"  despues: {res_post['texto'] or '(ninguno) OK'}")
        else:                                      # 3.1.b sin texto recuperable -> median blur
            print("OCR -> el consenso no recupero texto. Fallback: median blur global.")
            san = model_robust_median(image_path)
            mostrar_median(image_path, san)
    else:                                          # 3.2 NO ATAQUE -> grid
        print("Imagen CLEAN. Mostrando grid de reconstrucciones.")
        mostrar_grid_ocr(image_path)

    print("=" * 80)
    return {'pred': pred, 'etiqueta': etiqueta, 'proba': prob.tolist()}

resultado = pipeline(
    "/content/drive/MyDrive/Imagenes tesis/POCBicubic.png",
    modelo,
)