# -*- coding: utf-8 -*-
"""Justificacion_Fourier_Features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VgFWnWlHZrW-d6RmVxHFXDn-o2qUy4l6

# 📊 Justificación del uso de la Transformada de Fourier como Feature

Este notebook demuestra **visualmente y cuantitativamente** por qué la Transformada de Fourier (FFT) es una feature discriminativa para detectar imágenes procesadas por Anamorpher (bicubic/bilinear downsampling).

La idea central: el proceso de downsampling introduce **patrones espectrales sistemáticos** que no aparecen en imágenes originales (clean). Estos patrones son invisibles al ojo humano pero claramente visibles en el dominio de la frecuencia.

**Estructura del análisis:**
1. Comparación visual imagen clean vs ataque (igual que en literatura de adversarial examples)
2. Comparación de sus espectros de Fourier
3. Diferencias pixel a pixel y espectrales
4. Análisis estadístico de separabilidad espectral
"""

!pip install scikit-learn seaborn scipy pillow matplotlib -q

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns
from PIL import Image
from scipy.stats import ks_2samp
import os
from pathlib import Path

from google.colab import drive
drive.mount('/content/drive')

"""## ⚙️ Configuración de rutas"""

BASE = "/content/drive/MyDrive/fourier"

CLEAN_DIR   = os.path.join(BASE,'clean')

BICUBIC_DIR = os.path.join(BASE,'ataque')
BILINEAR_DIR = os.path.join(BASE,'bilinear')

# Verificar que existen
for d in [CLEAN_DIR, BICUBIC_DIR,BILINEAR_DIR]:
    files = [f for f in os.listdir(d) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    print(f"{d}: {files} imágenes")

"""## 🔧 Funciones auxiliares"""

IMG_SIZE = (255, 255)  # Tamaño de trabajo para visualizaciones (igual que en tu modelo)

def load_img(path, size=IMG_SIZE):
    """Carga imagen y la redimensiona."""
    return np.array(Image.open(path).convert('RGB').resize(size,Image.NEAREST))

def get_fourier_spectrum(img_rgb, channel_idx):

    img_hsv = mcolors.rgb_to_hsv(img_rgb / 255.0)
    channel = img_hsv[:, :, channel_idx]
    fft     = np.fft.fft2(channel)
    mag     = np.abs(np.fft.fftshift(fft))
    return np.log1p(mag)

def get_all_spectra(img_rgb):
    """Retorna espectros de los 3 canales HSV."""
    img_hsv = mcolors.rgb_to_hsv(img_rgb / 255.0)
    spectra = {}
    for i, name in enumerate(['Hue', 'Sat', 'Val']):
        fft = np.fft.fft2(img_hsv[:, :, i])
        mag = np.abs(np.fft.fftshift(fft))
        spectra[name] = np.log1p(mag)
    return spectra

def pick_random_img(directory):
    """Selecciona una imagen al azar del directorio."""
    files = [f for f in os.listdir(directory) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    path  = os.path.join(directory, np.random.choice(files))
    return path, load_img(path)

print("Funciones cargadas ✅")

"""## 📸 Parte 1: Comparación visual — Clean vs Ataque

Reproducimos la figura clásica de análisis espectral adversarial:
- Imagen original (clean)
- Imagen atacada (bicubic/bilinear downsampling)
- Diferencia pixel a pixel
- Espectro de Fourier de cada una
- Diferencia espectral

**Hipótesis:** si el downsampling introduce artefactos espectrales sistemáticos, deberían verse patrones claros en la diferencia de espectros.
"""

np.random.seed(42)

path_clean,  img_clean  = pick_random_img(CLEAN_DIR)
path_attack_bic, img_attack_bic = pick_random_img(BICUBIC_DIR)
path_attack_bil, img_attack_bil = pick_random_img(BILINEAR_DIR)

spec_clean      = get_fourier_spectrum(img_clean, channel_idx=0)
spec_attack_bic = get_fourier_spectrum(img_attack_bic, channel_idx=0)
spec_attack_bil = get_fourier_spectrum(img_attack_bil, channel_idx=0)

# Diferencias
pixel_diff_bic = img_attack_bic.astype(int) - img_clean.astype(int)
pixel_diff_bil = img_attack_bil.astype(int) - img_clean.astype(int)
pixel_diff_clean = img_clean.astype(int) - img_clean.astype(int)

# Espectros de diferencia

spec_diff_bic = np.abs(spec_attack_bic - spec_clean)
spec_diff_bil = np.abs(spec_attack_bil - spec_clean)
spec_diff_clean = np.abs(spec_clean-spec_clean)

# Visualización amplificada
pixel_diff_vis_bic = np.clip(pixel_diff_bic + 128, 0, 255).astype(np.uint8)
pixel_diff_vis_bil = np.clip(pixel_diff_bil + 128, 0, 255).astype(np.uint8)
pixel_diff_vis_clean= np.clip(pixel_diff_clean + 128, 0, 255).astype(np.uint8)

# Figura
fig, axes = plt.subplots(3, 3, figsize=(15, 14))

fig.suptitle(
    'Análisis espectral: Clean vs Anamorpher (Bicubic y Bilinear)',
    fontsize=16,
    fontweight='bold'
)

# =========================
# FILA 1 — CLEAN
# =========================
axes[0, 0].imshow(img_clean)
axes[0, 0].set_title('Imagen limpia')
axes[0, 0].axis('off')

axes[0, 1].imshow(spec_clean, cmap='viridis')
axes[0, 1].set_title('FFT Clean')
axes[0, 1].axis('off')


axes[0, 2].imshow(spec_diff_clean, cmap='viridis')
axes[0, 2].set_title('Diferencia espectral Limpia - Limpia')
axes[0, 2].axis('off')

# =========================
# FILA 2 — BICUBIC
# =========================
axes[1, 0].imshow(img_attack_bic)
axes[1, 0].set_title('Ataque Bicubic')
axes[1, 0].axis('off')

axes[1, 1].imshow(spec_attack_bic, cmap='viridis')
axes[1, 1].set_title('FFT Bicubic')
axes[1, 1].axis('off')

axes[1, 2].imshow(spec_diff_bic, cmap='viridis')
axes[1, 2].set_title('Diferencia espectral Bicubica - Limpia')
axes[1, 2].axis('off')

# =========================
# FILA 3 — BILINEAR
# =========================
axes[2, 0].imshow(img_attack_bil)
axes[2, 0].set_title('Ataque Bilinear')
axes[2, 0].axis('off')

axes[2, 1].imshow(spec_attack_bil, cmap='viridis')
axes[2, 1].set_title('FFT Bilinear')
axes[2, 1].axis('off')

axes[2, 2].imshow(spec_diff_bil, cmap='viridis')
axes[2, 2].set_title('Diferencia del espectral Bilinear - Limpia')
axes[2, 2].axis('off')

plt.tight_layout()

plt.savefig(
    'fourier_comparacion_visual.png',
    dpi=150,
    bbox_inches='tight'
)

plt.show()

print("\n🔍 Observación: notar patrones estructurados en las diferencias espectrales")

print(f"Clean:     {path_clean.split('/')[-1]}")
print(f"Bicubic:   {path_attack_bic.split('/')[-1]}")
print(f"Bilinear:  {path_attack_bil.split('/')[-1]}")

"""## 📊 Parte 2: Espectros promedio sobre toda la clase

Un solo ejemplo puede ser anecdótico. Acá calculamos el **espectro promedio de toda la clase clean y toda la clase ataque** para ver si el patrón es sistemático.
"""

def compute_mean_spectrum(directory, channel_idx=2, max_imgs=200):
    """Calcula el espectro de Fourier promedio de una clase."""
    files = [f for f in os.listdir(directory)
             if f.lower().endswith(('.png', '.jpg', '.jpeg'))][:max_imgs]
    spectra = []
    for fname in files:
        try:
            img  = load_img(os.path.join(directory, fname))
            spec = get_fourier_spectrum(img, channel_idx)
            spectra.append(spec)
        except Exception as e:
            print(f"Error en {fname}: {e}")
    return np.mean(spectra, axis=0), np.std(spectra, axis=0)

print("Calculando espectros promedio (puede tardar unos segundos)...")
mean_spec_clean,  std_spec_clean  = compute_mean_spectrum(CLEAN_DIR)
mean_spec_attack, std_spec_attack = compute_mean_spectrum(BICUBIC_DIR)
print("✅ Listo")

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('Espectro de Fourier promedio por clase (canal Value)',
             fontsize=13, fontweight='bold')

vmin = min(mean_spec_clean.min(), mean_spec_attack.min())
vmax = max(mean_spec_clean.max(), mean_spec_attack.max())

im0 = axes[0].imshow(mean_spec_clean, cmap='viridis', vmin=vmin, vmax=vmax)
axes[0].set_title('Espectro medio — CLEAN', fontsize=11)
axes[0].axis('off')
plt.colorbar(im0, ax=axes[0], fraction=0.046)

im1 = axes[1].imshow(mean_spec_attack, cmap='viridis', vmin=vmin, vmax=vmax)
axes[1].set_title('Espectro medio — ATAQUE (bicubic)', fontsize=11)
axes[1].axis('off')
plt.colorbar(im1, ax=axes[1], fraction=0.046)

diff = np.abs(mean_spec_attack - mean_spec_clean)
im2 = axes[2].imshow(diff, cmap='hot')
axes[2].set_title('Diferencia media |ataque - clean|', fontsize=11)
axes[2].axis('off')
plt.colorbar(im2, ax=axes[2], fraction=0.046)

plt.tight_layout()
plt.savefig('fourier_espectros_promedio.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n📌 Diferencia espectral media: {diff.mean():.4f} ± {diff.std():.4f}")
print("   Si hay patrones estructurados en el mapa de diferencia, la FFT es discriminativa.")

"""## 📉 Parte 3: Perfil espectral radial

Colapsamos el espectro 2D en un perfil 1D promediando por frecuencia radial. Esto permite ver si hay frecuencias específicas donde las clases difieren más.
"""

def radial_profile(spectrum):
    """Promedia el espectro por banda de frecuencia radial."""
    h, w = spectrum.shape
    cy, cx = h // 2, w // 2
    y, x   = np.ogrid[:h, :w]
    r      = np.sqrt((x - cx)**2 + (y - cy)**2).astype(int)
    max_r  = min(cy, cx)
    profile = np.array([spectrum[r == i].mean() if (r == i).any() else 0
                        for i in range(max_r)])
    return profile

profile_clean  = radial_profile(mean_spec_clean)
profile_attack = radial_profile(mean_spec_attack)
freqs = np.arange(len(profile_clean))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Perfil espectral radial: distribución de energía por frecuencia',
             fontsize=13, fontweight='bold')

# Perfil absoluto
axes[0].plot(freqs, profile_clean,  color='steelblue',   lw=2, label='Clean')
axes[0].plot(freqs, profile_attack, color='darkorange',  lw=2, label='Ataque (bicubic)', linestyle='--')
axes[0].set_xlabel('Frecuencia radial (píxeles desde centro)')
axes[0].set_ylabel('Magnitud log promedio')
axes[0].set_title('Energía espectral por frecuencia radial')
axes[0].legend()
axes[0].grid(alpha=0.3)

# Diferencia
diff_profile = profile_attack - profile_clean
axes[1].fill_between(freqs, diff_profile, alpha=0.4,
                     color=np.where(diff_profile > 0, 'darkorange', 'steelblue')[0])
axes[1].plot(freqs, diff_profile, color='black', lw=1.5)
axes[1].axhline(0, color='gray', lw=1, linestyle='--')
axes[1].set_xlabel('Frecuencia radial')
axes[1].set_ylabel('Diferencia (ataque - clean)')
axes[1].set_title('Diferencia de energía espectral por frecuencia')
axes[1].grid(alpha=0.3)

# Marcar zona de máxima diferencia
peak_idx = np.argmax(np.abs(diff_profile))
axes[1].axvline(peak_idx, color='red', lw=1.5, linestyle=':', label=f'Máx. dif. en f={peak_idx}')
axes[1].legend()

plt.tight_layout()
plt.savefig('fourier_perfil_radial.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n📌 Frecuencia con mayor diferencia entre clases: {peak_idx}")
print(f"   Diferencia en ese punto: {diff_profile[peak_idx]:.4f}")

"""## 🔬 Parte 4: Separabilidad espectral por canal HSV

Revisamos si el patrón espectral es consistente en los 3 canales (Hue, Saturation, Value) usando el estadístico KS (Kolmogorov-Smirnov) igual que en el notebook principal.
"""

def extract_fft_features_full(img_rgb):
    """Extrae mean, std, max del espectro de cada canal HSV."""
    img_hsv = mcolors.rgb_to_hsv(img_rgb / 255.0)
    feats = {}
    for i, name in enumerate(['Hue', 'Sat', 'Val']):
        fft    = np.fft.fft2(img_hsv[:, :, i])
        mag    = np.abs(np.fft.fftshift(fft))
        log_m  = np.log1p(mag)
        feats[f'FFT_mean_{name}'] = log_m.mean()
        feats[f'FFT_std_{name}']  = log_m.std()
        feats[f'FFT_max_{name}']  = log_m.max()
    return feats

def collect_features(directory, label, max_imgs=200):
    files  = [f for f in os.listdir(directory)
              if f.lower().endswith(('.png','.jpg','.jpeg'))][:max_imgs]
    rows   = []
    for fname in files:
        try:
            img  = load_img(os.path.join(directory, fname))
            feats = extract_fft_features_full(img)
            feats['label'] = label
            rows.append(feats)
        except: pass
    return rows

import pandas as pd

print("Extrayendo features FFT...")
rows_clean  = collect_features(CLEAN_DIR,   'clean')
rows_attack = collect_features(BICUBIC_DIR, 'ataque')
df = pd.DataFrame(rows_clean + rows_attack)
print(f"Dataset: {df.shape[0]} imágenes, {df.shape[1]-1} features")
df.head()

feature_cols = [c for c in df.columns if c != 'label']
mask_clean  = df['label'] == 'clean'
mask_attack = df['label'] == 'ataque'

ks_results = {}
for feat in feature_cols:
    stat, p = ks_2samp(df.loc[mask_clean, feat], df.loc[mask_attack, feat])
    ks_results[feat] = {'KS_stat': stat, 'p_value': p}

df_ks = pd.DataFrame(ks_results).T.sort_values('KS_stat', ascending=False)

fig, ax = plt.subplots(figsize=(10, 5))
colors = ['#2ecc71' if v > 0.3 else '#e74c3c' if v < 0.1 else '#f39c12'
          for v in df_ks['KS_stat']]
bars = ax.barh(df_ks.index, df_ks['KS_stat'], color=colors)
ax.axvline(0.3, color='green',  lw=1.5, linestyle='--', label='Alta separabilidad (>0.3)')
ax.axvline(0.1, color='orange', lw=1.5, linestyle='--', label='Baja separabilidad (<0.1)')
ax.set_xlabel('Estadístico KS (0=idénticas, 1=completamente separadas)')
ax.set_title('Separabilidad de features FFT: estadístico KS por feature', fontweight='bold')
ax.legend()
ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig('fourier_separabilidad_ks.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 Separabilidad (KS) por feature FFT:")
print(df_ks.to_string())

"""## 📦 Parte 5: Distribuciones feature a feature

Igual que en tu notebook de histogramas, pero solo para las features FFT.
"""

fig, axes = plt.subplots(3, 3, figsize=(14, 10))
axes = axes.flatten()
fig.suptitle('Distribución de features FFT: Clean vs Ataque\n(más separación = más discriminativa)',
             fontsize=13, fontweight='bold')

for i, feat in enumerate(feature_cols):
    ax = axes[i]
    vals_clean  = df.loc[mask_clean,  feat]
    vals_attack = df.loc[mask_attack, feat]

    ax.hist(vals_clean,  bins=20, alpha=0.6, color='steelblue',  label='Clean',  density=True)
    ax.hist(vals_attack, bins=20, alpha=0.6, color='darkorange', label='Ataque', density=True)

    ks_val = ks_results[feat]['KS_stat']
    p_val  = ks_results[feat]['p_value']
    color_title = 'darkgreen' if ks_val > 0.3 else ('red' if ks_val < 0.1 else 'darkorange')

    ax.set_title(f"{feat}\nKS={ks_val:.3f}, p={p_val:.2e}",
                 fontsize=8, color=color_title)
    ax.tick_params(labelsize=7)
    ax.set_yticks([])
    if i == 0:
        ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig('fourier_distribuciones_features.png', dpi=150, bbox_inches='tight')
plt.show()

"""## 🎯 Parte 6: Visualización del espacio de features (PCA 2D)

Reducimos las 9 features FFT a 2 dimensiones para verificar que hay separación entre clases.
"""

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X = df[feature_cols].values
y = (df['label'] == 'ataque').astype(int).values

X_scaled = StandardScaler().fit_transform(X)
X_pca    = PCA(n_components=2).fit_transform(X_scaled)

fig, ax = plt.subplots(figsize=(8, 6))
scatter_clean  = ax.scatter(X_pca[y==0, 0], X_pca[y==0, 1],
                            c='steelblue', alpha=0.6, label='Clean',  s=30, edgecolors='white', lw=0.5)
scatter_attack = ax.scatter(X_pca[y==1, 0], X_pca[y==1, 1],
                            c='darkorange', alpha=0.6, label='Ataque', s=30, edgecolors='white', lw=0.5)
ax.set_xlabel('PC 1')
ax.set_ylabel('PC 2')
ax.set_title('Espacio de features FFT — PCA 2D\n(separación visual = features discriminativas)',
             fontweight='bold')
ax.legend(fontsize=11)
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('fourier_pca_2d.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📌 Si los clusters están bien separados en PCA 2D,")
print("   la FFT captura información discriminativa para el clasificador SVM.")

"""## ✅ Resumen de la justificación

Este análisis muestra que la Transformada de Fourier es una feature justificada para el detector de Anamorpher porque:

1. **Visualmente:** el downsampling bicubic/bilinear introduce artefactos espectrales sistemáticos visibles en el espectro de magnitud FFT pero imperceptibles en el espacio de píxeles.

2. **Estadísticamente:** el estadístico KS mide la separabilidad entre distribuciones de features FFT de imágenes clean vs atacadas. Las features con KS > 0.3 indican que las distribuciones son significativamente distintas entre clases.

3. **Geométricamente:** la proyección PCA 2D muestra que el espacio de features FFT tiene estructura separable, lo que le da al SVM margen para encontrar un hiperplano discriminativo.

4. **Complementariedad:** junto con las features HSI, la FFT aporta información del dominio frecuencial que las estadísticas de color no capturan.

> **Referencia conceptual:** este enfoque sigue la línea de trabajos como *"Unmasking the Abnormal Events in Video" (Ionescu et al.)* y análisis de adversarial examples en el dominio frecuencial (Guo et al., 2019), que muestran que ataques y transformaciones introducen patrones de alta frecuencia detectables con FFT.
"""